{"variants":[{"paths":["\/documentation\/obusdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/obusdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CommonAlertPointDetected","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedAlertPointDetected","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedDeductionSuccessful","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedEnteringPricedRoad","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedDeductionSuccessful","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPCPOInformation","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedDeductionSuccessful","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedDeductionSuccessful","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERPEvent","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedAlertPointDetected","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedDeductionSuccessful","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedEnteringPricedRoad","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Logger","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockBuilder","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockEvent","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockSetting","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingInformation","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKManager","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedAlertPointDetected","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedCharging","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedDeductionFailure","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedDeductionSuccessful"]},{"title":"Protocols","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/LoggerProtocol","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUBaseTraffic","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUConnectionDelegate","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUDataDelegate"]},{"title":"Structures","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBU","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUAcceleration","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUData","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUPaymentHistory","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextWithStyle","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTotalTripCharged","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficParking","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficText","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTravelSummary","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTravelTime","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Parking","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/TravelTime"]},{"title":"Functions","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/getChargingHistory()"]},{"title":"Type Aliases","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CompletionHandler","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Handler","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/JSON","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUImageRef"]},{"title":"Enumerations","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/BluetoothState","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CompletionResult","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/HandlerResult","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ItemTTS","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUBusinessFunction","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUCardStatus","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingMessageType","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingPaymentMode","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingType","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUErrorCode","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUPaymentMode","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextColor","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextStyle","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficDataPriority","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficInfo","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficMessageType","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/TdcidEvent"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"OBUSDK","title":"OBUSDK","symbolKind":"module","role":"collection","modules":[{"name":"OBUSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUChargingType":{"role":"symbol","title":"OBUChargingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUChargingType"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUChargingType"}],"url":"\/documentation\/obusdk\/obuchargingtype"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EEPBasedDeductionFailure":{"role":"symbol","title":"EEPBasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EEPBasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EEPBasedDeductionFailure"}],"url":"\/documentation\/obusdk\/eepbaseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/CompletionHandler":{"role":"symbol","title":"CompletionHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionHandler"}],"abstract":[{"type":"text","text":"A type that can convert itself into and out of an external representation."},{"type":"text","text":" "},{"type":"codeVoice","code":"CompletionHandler"},{"type":"text","text":" is a type alias of a value that represents a completion,"},{"type":"text","text":" "},{"type":"text","text":"including an associated value in each case."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CompletionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompletionHandler"}],"url":"\/documentation\/obusdk\/completionhandler"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUPaymentMode":{"role":"symbol","title":"OBUPaymentMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUPaymentMode"}],"abstract":[{"type":"text","text":"Payment mode for the charged Business Function."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUPaymentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUPaymentMode"}],"url":"\/documentation\/obusdk\/obupaymentmode"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUBusinessFunction":{"role":"symbol","title":"OBUBusinessFunction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUBusinessFunction"}],"abstract":[{"type":"text","text":"There are five different business types for charging."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUBusinessFunction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUBusinessFunction"}],"url":"\/documentation\/obusdk\/obubusinessfunction"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUSDKManager":{"role":"symbol","title":"OBUSDKManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUSDKManager"}],"abstract":[{"type":"text","text":"This class is the entry point for the SDK and provides access to all the resources that developers need to create third-party applications."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUSDKManager"}],"url":"\/documentation\/obusdk\/obusdkmanager"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUAcceleration":{"role":"symbol","title":"OBUAcceleration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUAcceleration"}],"abstract":[{"type":"text","text":"Acceleration of the connected OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUAcceleration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUAcceleration"}],"url":"\/documentation\/obusdk\/obuacceleration"},"doc://sg.gov.lta.extol/documentation/OBUSDK/PointBasedDeductionFailure":{"role":"symbol","title":"PointBasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointBasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointBasedDeductionFailure"}],"url":"\/documentation\/obusdk\/pointbaseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTrafficText":{"role":"symbol","title":"OBUTrafficText","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTrafficText"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTrafficText"}],"url":"\/documentation\/obusdk\/obutraffictext"},"doc://sg.gov.lta.extol/documentation/OBUSDK/BluetoothState":{"role":"symbol","title":"BluetoothState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothState"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/BluetoothState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BluetoothState"}],"url":"\/documentation\/obusdk\/bluetoothstate"},"doc://sg.gov.lta.extol/documentation/OBUSDK/Parking":{"role":"symbol","title":"Parking","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parking"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Parking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Parking"}],"url":"\/documentation\/obusdk\/parking"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EntryExitBasedEnteringPricedRoad":{"role":"symbol","title":"EntryExitBasedEnteringPricedRoad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryExitBasedEnteringPricedRoad"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedEnteringPricedRoad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EntryExitBasedEnteringPricedRoad"}],"url":"\/documentation\/obusdk\/entryexitbasedenteringpricedroad"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTotalTripCharged":{"role":"symbol","title":"OBUTotalTripCharged","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTotalTripCharged"}],"abstract":[{"type":"text","text":"Total Trip Charged values from the connected OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTotalTripCharged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTotalTripCharged"}],"url":"\/documentation\/obusdk\/obutotaltripcharged"},"doc://sg.gov.lta.extol/documentation/OBUSDK/TdcidEvent":{"role":"symbol","title":"TdcidEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TdcidEvent"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/TdcidEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TdcidEvent"}],"url":"\/documentation\/obusdk\/tdcidevent"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EntryExitBasedDeductionFailure":{"role":"symbol","title":"EntryExitBasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryExitBasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EntryExitBasedDeductionFailure"}],"url":"\/documentation\/obusdk\/entryexitbaseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/ERP1BasedDeductionFailure":{"role":"symbol","title":"ERP1BasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERP1BasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ERP1BasedDeductionFailure"}],"url":"\/documentation\/obusdk\/erp1baseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTextColor":{"role":"symbol","title":"OBUTextColor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTextColor"}],"abstract":[{"type":"text","text":"Color of the Screen text items"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTextColor"}],"url":"\/documentation\/obusdk\/obutextcolor"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EPSBasedDeductionSuccessful":{"role":"symbol","title":"EPSBasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPSBasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EPSBasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/epsbaseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUData":{"role":"symbol","title":"OBUData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUData"}],"abstract":[{"type":"text","text":"Contains complete data from the OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUData"}],"url":"\/documentation\/obusdk\/obudata"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EPSBasedCharging":{"role":"symbol","title":"EPSBasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPSBasedCharging"}],"abstract":[{"type":"text","text":"EPS-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EPSBasedCharging"}],"url":"\/documentation\/obusdk\/epsbasedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUDataDelegate":{"role":"symbol","title":"OBUDataDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUDataDelegate"}],"abstract":[{"type":"text","text":"Optional callbacks for receiving data from a connected OBU."},{"type":"text","text":" "},{"type":"text","text":"Implementing these methods will trigger when data is received."},{"type":"text","text":" "},{"type":"text","text":"Each method corresponds to a different type of data that can be received from the OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUDataDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUDataDelegate"}],"url":"\/documentation\/obusdk\/obudatadelegate"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUChargingMessageType":{"role":"symbol","title":"OBUChargingMessageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUChargingMessageType"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingMessageType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUChargingMessageType"}],"url":"\/documentation\/obusdk\/obuchargingmessagetype"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EntryExitBasedDeductionSuccessful":{"role":"symbol","title":"EntryExitBasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryExitBasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EntryExitBasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/entryexitbaseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/HandlerResult":{"role":"symbol","title":"HandlerResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandlerResult"}],"abstract":[{"type":"text","text":"A value that represents either a success or a failure, including an"},{"type":"text","text":" "},{"type":"text","text":"associated value in each case."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/HandlerResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HandlerResult"}],"url":"\/documentation\/obusdk\/handlerresult"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTravelTime":{"role":"symbol","title":"OBUTravelTime","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTravelTime"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTravelTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTravelTime"}],"url":"\/documentation\/obusdk\/obutraveltime"},"doc://sg.gov.lta.extol/documentation/OBUSDK/Handler":{"role":"symbol","title":"Handler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Handler"}],"abstract":[{"type":"text","text":"A type that can convert itself into and out of an external representation."},{"type":"text","text":" "},{"type":"codeVoice","code":"Handler"},{"type":"text","text":" is a type alias of a value that represents either a success or a failure,"},{"type":"text","text":" "},{"type":"text","text":"including an associated value in each case."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Handler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Handler"}],"url":"\/documentation\/obusdk\/handler"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTravelSummary":{"role":"symbol","title":"OBUTravelSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTravelSummary"}],"abstract":[{"type":"text","text":"Travel Summary of the connected OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTravelSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTravelSummary"}],"url":"\/documentation\/obusdk\/obutravelsummary"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUSDKVersionString":{"role":"symbol","title":"OBUSDKVersionString","fragments":[{"kind":"identifier","text":"OBUSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for OBUSDK."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/obusdk\/obusdkversionstring"},"doc://sg.gov.lta.extol/documentation/OBUSDK/DistanceBasedDeductionSuccessful":{"role":"symbol","title":"DistanceBasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistanceBasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistanceBasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/distancebaseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUCardStatus":{"role":"symbol","title":"OBUCardStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUCardStatus"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUCardStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUCardStatus"}],"url":"\/documentation\/obusdk\/obucardstatus"},"doc://sg.gov.lta.extol/documentation/OBUSDK/ERP1BasedDeductionSuccessful":{"role":"symbol","title":"ERP1BasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERP1BasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ERP1BasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/erp1baseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUChargingInformation":{"role":"symbol","title":"OBUChargingInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUChargingInformation"}],"abstract":[{"type":"text","text":"Charging Information of the connected OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUChargingInformation"}],"url":"\/documentation\/obusdk\/obucharginginformation"},"doc://sg.gov.lta.extol/documentation/OBUSDK/JSON":{"role":"symbol","title":"JSON","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSON"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/JSON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSON"}],"url":"\/documentation\/obusdk\/json"},"doc://sg.gov.lta.extol/documentation/OBUSDK/getChargingHistory()":{"role":"symbol","title":"getChargingHistory()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChargingHistory"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"OBUPaymentHistory","preciseIdentifier":"s:6OBUSDK17OBUPaymentHistoryV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/getChargingHistory()","kind":"symbol","type":"topic","url":"\/documentation\/obusdk\/getcharginghistory()"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EEPBasedDeductionSuccessful":{"role":"symbol","title":"EEPBasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EEPBasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EEPBasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/eepbaseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUChargingPaymentMode":{"role":"symbol","title":"OBUChargingPaymentMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUChargingPaymentMode"}],"abstract":[{"type":"text","text":"Payment mode for the charged Business Function."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUChargingPaymentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUChargingPaymentMode"}],"url":"\/documentation\/obusdk\/obuchargingpaymentmode"},"doc://sg.gov.lta.extol/documentation/OBUSDK/PointBasedCharging":{"role":"symbol","title":"PointBasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointBasedCharging"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointBasedCharging"}],"url":"\/documentation\/obusdk\/pointbasedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/ERP1BasedCharging":{"role":"symbol","title":"ERP1BasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERP1BasedCharging"}],"abstract":[{"type":"text","text":"ERP1-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERP1BasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ERP1BasedCharging"}],"url":"\/documentation\/obusdk\/erp1basedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/MockEvent":{"role":"symbol","title":"MockEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockEvent"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockEvent"}],"url":"\/documentation\/obusdk\/mockevent"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUConnectionDelegate":{"role":"symbol","title":"OBUConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUConnectionDelegate"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUConnectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUConnectionDelegate"}],"url":"\/documentation\/obusdk\/obuconnectiondelegate"},"doc://sg.gov.lta.extol/documentation/OBUSDK/Logger":{"role":"symbol","title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/Logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/obusdk\/logger"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTrafficParking":{"role":"symbol","title":"OBUTrafficParking","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTrafficParking"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficParking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTrafficParking"}],"url":"\/documentation\/obusdk\/obutrafficparking"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EEPBasedCharging":{"role":"symbol","title":"EEPBasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EEPBasedCharging"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPBasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EEPBasedCharging"}],"url":"\/documentation\/obusdk\/eepbasedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/DistanceBasedAlertPointDetected":{"role":"symbol","title":"DistanceBasedAlertPointDetected","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistanceBasedAlertPointDetected"}],"abstract":[{"type":"text","text":"Distance-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedAlertPointDetected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistanceBasedAlertPointDetected"}],"url":"\/documentation\/obusdk\/distancebasedalertpointdetected"},"doc://sg.gov.lta.extol/documentation/OBUSDK/PointBasedDeductionSuccessful":{"role":"symbol","title":"PointBasedDeductionSuccessful","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointBasedDeductionSuccessful"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedDeductionSuccessful","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointBasedDeductionSuccessful"}],"url":"\/documentation\/obusdk\/pointbaseddeductionsuccessful"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTrafficDataPriority":{"role":"symbol","title":"OBUTrafficDataPriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTrafficDataPriority"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficDataPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTrafficDataPriority"}],"url":"\/documentation\/obusdk\/obutrafficdatapriority"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUPaymentHistory":{"role":"symbol","title":"OBUPaymentHistory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUPaymentHistory"}],"abstract":[{"type":"text","text":"Paynent History received in every response coming from the OBU."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUPaymentHistory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUPaymentHistory"}],"url":"\/documentation\/obusdk\/obupaymenthistory"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUErrorCode":{"role":"symbol","title":"OBUErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUErrorCode"}],"abstract":[{"type":"text","text":"List of Errors."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUErrorCode"}],"url":"\/documentation\/obusdk\/obuerrorcode"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EntryExitBasedAlertPointDetected":{"role":"symbol","title":"EntryExitBasedAlertPointDetected","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryExitBasedAlertPointDetected"}],"abstract":[{"type":"text","text":"Entry\/Exit-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedAlertPointDetected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EntryExitBasedAlertPointDetected"}],"url":"\/documentation\/obusdk\/entryexitbasedalertpointdetected"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTrafficMessageType":{"role":"symbol","title":"OBUTrafficMessageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTrafficMessageType"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficMessageType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTrafficMessageType"}],"url":"\/documentation\/obusdk\/obutrafficmessagetype"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTextStyle":{"role":"symbol","title":"OBUTextStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTextStyle"}],"abstract":[{"type":"text","text":"Font of the Screen text items"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTextStyle"}],"url":"\/documentation\/obusdk\/obutextstyle"},"doc://sg.gov.lta.extol/documentation/OBUSDK/PointBasedAlertPointDetected":{"role":"symbol","title":"PointBasedAlertPointDetected","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointBasedAlertPointDetected"}],"abstract":[{"type":"text","text":"Point-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/PointBasedAlertPointDetected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointBasedAlertPointDetected"}],"url":"\/documentation\/obusdk\/pointbasedalertpointdetected"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EPSBasedDeductionFailure":{"role":"symbol","title":"EPSBasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPSBasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EPSBasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EPSBasedDeductionFailure"}],"url":"\/documentation\/obusdk\/epsbaseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTextWithStyle":{"role":"symbol","title":"OBUTextWithStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTextWithStyle"}],"abstract":[{"type":"text","text":"OBUTextWithStyle"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTextWithStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTextWithStyle"}],"url":"\/documentation\/obusdk\/obutextwithstyle"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EntryExitBasedCharging":{"role":"symbol","title":"EntryExitBasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryExitBasedCharging"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EntryExitBasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EntryExitBasedCharging"}],"url":"\/documentation\/obusdk\/entryexitbasedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/ItemTTS":{"role":"symbol","title":"ItemTTS","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ItemTTS"}],"abstract":[{"type":"text","text":"Whether  TTS is enabled or not"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ItemTTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ItemTTS"}],"url":"\/documentation\/obusdk\/itemtts"},"doc://sg.gov.lta.extol/documentation/OBUSDK/MockSetting":{"role":"symbol","title":"MockSetting","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockSetting"}],"abstract":[{"type":"text","text":"Mock settings used by developers to set Mock Data"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockSetting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockSetting"}],"url":"\/documentation\/obusdk\/mocksetting"},"doc://sg.gov.lta.extol/documentation/OBUSDK/DistanceBasedCharging":{"role":"symbol","title":"DistanceBasedCharging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistanceBasedCharging"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedCharging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistanceBasedCharging"}],"url":"\/documentation\/obusdk\/distancebasedcharging"},"doc://sg.gov.lta.extol/documentation/OBUSDK/MockBuilder":{"role":"symbol","title":"MockBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockBuilder"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/MockBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockBuilder"}],"url":"\/documentation\/obusdk\/mockbuilder"},"doc://sg.gov.lta.extol/documentation/OBUSDK/CommonAlertPointDetected":{"role":"symbol","title":"CommonAlertPointDetected","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonAlertPointDetected"}],"abstract":[{"type":"text","text":"Common Event"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CommonAlertPointDetected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonAlertPointDetected"}],"url":"\/documentation\/obusdk\/commonalertpointdetected"},"doc://sg.gov.lta.extol/documentation/OBUSDK/LoggerProtocol":{"role":"symbol","title":"LoggerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerProtocol"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/LoggerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerProtocol"}],"url":"\/documentation\/obusdk\/loggerprotocol"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUTrafficInfo":{"role":"symbol","title":"OBUTrafficInfo","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUTrafficInfo"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUTrafficInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUTrafficInfo"}],"url":"\/documentation\/obusdk\/obutrafficinfo"},"doc://sg.gov.lta.extol/documentation/OBUSDK/ERPEvent":{"role":"symbol","title":"ERPEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERPEvent"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/ERPEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ERPEvent"}],"url":"\/documentation\/obusdk\/erpevent"},"doc://sg.gov.lta.extol/documentation/OBUSDK/DistanceBasedEnteringPricedRoad":{"role":"symbol","title":"DistanceBasedEnteringPricedRoad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistanceBasedEnteringPricedRoad"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedEnteringPricedRoad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistanceBasedEnteringPricedRoad"}],"url":"\/documentation\/obusdk\/distancebasedenteringpricedroad"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUBaseTraffic":{"role":"symbol","title":"OBUBaseTraffic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUBaseTraffic"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUBaseTraffic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUBaseTraffic"}],"url":"\/documentation\/obusdk\/obubasetraffic"},"doc://sg.gov.lta.extol/documentation/OBUSDK/DistanceBasedDeductionFailure":{"role":"symbol","title":"DistanceBasedDeductionFailure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DistanceBasedDeductionFailure"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/DistanceBasedDeductionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DistanceBasedDeductionFailure"}],"url":"\/documentation\/obusdk\/distancebaseddeductionfailure"},"doc://sg.gov.lta.extol/documentation/OBUSDK/EEPCPOInformation":{"role":"symbol","title":"EEPCPOInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EEPCPOInformation"}],"abstract":[{"type":"text","text":"EEP-based Events"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/EEPCPOInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EEPCPOInformation"}],"url":"\/documentation\/obusdk\/eepcpoinformation"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUSDKVersionNumber":{"role":"symbol","title":"OBUSDKVersionNumber","fragments":[{"kind":"identifier","text":"OBUSDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for OBUSDK."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/obusdk\/obusdkversionnumber"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBUImageRef":{"role":"symbol","title":"OBUImageRef","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBUImageRef"}],"abstract":[{"type":"text","text":"The data type of the image references in OBU response."},{"type":"text","text":" "},{"type":"text","text":"It is a stringified integer"}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUImageRef","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBUImageRef"}],"url":"\/documentation\/obusdk\/obuimageref"},"doc://sg.gov.lta.extol/documentation/OBUSDK":{"role":"collection","title":"OBUSDK","abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK","kind":"symbol","type":"topic","url":"\/documentation\/obusdk"},"doc://sg.gov.lta.extol/documentation/OBUSDK/TravelTime":{"role":"symbol","title":"TravelTime","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelTime"}],"abstract":[],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/TravelTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelTime"}],"url":"\/documentation\/obusdk\/traveltime"},"doc://sg.gov.lta.extol/documentation/OBUSDK/CompletionResult":{"role":"symbol","title":"CompletionResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionResult"}],"abstract":[{"type":"text","text":"A value that represents a completion, including an"},{"type":"text","text":" "},{"type":"text","text":"associated value in each case."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/CompletionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompletionResult"}],"url":"\/documentation\/obusdk\/completionresult"},"doc://sg.gov.lta.extol/documentation/OBUSDK/OBU":{"role":"symbol","title":"OBU","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBU"}],"abstract":[{"type":"text","text":"Represents an OBU object."}],"identifier":"doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBU","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBU"}],"url":"\/documentation\/obusdk\/obu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKVersionNumber","doc:\/\/sg.gov.lta.extol\/documentation\/OBUSDK\/OBUSDKVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}